//! MultiBandBlender / pyrDown / pyrUp parity vs OpenCV fixtures
//! (tools/reference/fixtures/blend, generated by
//! tools/reference/gen_blend_fixtures.py against OpenCV 4.14.0).
//!
//! Every comparison here is BIT-EXACT, including the f32 weight pyramid:
//! the port replicates the exact FMA/lane structure of the 128-bit
//! universal-intrinsic build (NEON) the fixtures were recorded on — see the
//! notes in blend.rs and the generator. A mismatch means a port bug, not a
//! tolerance problem.

use panoloom_core::blend::{
    num_bands_for, pyr_down_f32, pyr_down_i16c3, pyr_up_i16c3, MultiBandBlender,
};
use panoloom_core::imgproc::GrayImage;
use serde_json::Value;
use std::path::PathBuf;

fn load(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tools/reference/fixtures/blend")
        .join(name);
    let data = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {} ({e}); run tools/reference/gen_blend_fixtures.py",
            path.display()
        )
    });
    serde_json::from_str(&data).expect("invalid fixture JSON")
}

fn i16_vec(v: &Value) -> Vec<i16> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| i16::try_from(x.as_i64().unwrap()).unwrap())
        .collect()
}

fn u8_vec(v: &Value) -> Vec<u8> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| u8::try_from(x.as_i64().unwrap()).unwrap())
        .collect()
}

fn f32_bits_vec(v: &Value) -> Vec<f32> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| f32::from_bits(u32::try_from(x.as_u64().unwrap()).unwrap()))
        .collect()
}

fn usize_at(v: &Value, key: &str) -> usize {
    v[key].as_u64().unwrap() as usize
}

fn assert_i16_eq(name: &str, got: &[i16], want: &[i16]) {
    assert_eq!(got.len(), want.len(), "{name}: length mismatch");
    let n_bad = got.iter().zip(want).filter(|(g, w)| g != w).count();
    if n_bad > 0 {
        let first = got.iter().zip(want).position(|(g, w)| g != w).unwrap();
        panic!(
            "{name}: {n_bad}/{} mismatches; first at [{first}]: got {} want {}",
            want.len(),
            got[first],
            want[first]
        );
    }
}

#[test]
fn pyrdown_i16c3_matches_opencv() {
    let fx = load("pyrdown_i16c3.json");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let (w, h) = (usize_at(case, "w"), usize_at(case, "h"));
        let src = i16_vec(&case["src"]);
        let (dst, dw, dh) = pyr_down_i16c3(&src, w, h);
        assert_eq!(
            (dw, dh),
            (usize_at(case, "dw"), usize_at(case, "dh")),
            "{name}: dst size"
        );
        assert_i16_eq(name, &dst, &i16_vec(&case["dst"]));
    }
}

#[test]
fn pyrup_i16c3_matches_opencv() {
    let fx = load("pyrup_i16c3.json");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let (w, h) = (usize_at(case, "w"), usize_at(case, "h"));
        let (dw, dh) = (usize_at(case, "dw"), usize_at(case, "dh"));
        let src = i16_vec(&case["src"]);
        let dst = pyr_up_i16c3(&src, w, h, dw, dh);
        assert_i16_eq(name, &dst, &i16_vec(&case["dst"]));
    }
}

#[test]
fn pyrdown_f32_matches_opencv_bitexact() {
    let fx = load("pyrdown_f32.json");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let (w, h) = (usize_at(case, "w"), usize_at(case, "h"));
        let src = f32_bits_vec(&case["src_bits"]);
        let want = f32_bits_vec(&case["dst_bits"]);
        let (dst, dw, dh) = pyr_down_f32(&src, w, h);
        assert_eq!(
            (dw, dh),
            (usize_at(case, "dw"), usize_at(case, "dh")),
            "{name}: dst size"
        );
        assert_eq!(dst.len(), want.len(), "{name}: length");
        let n_bad = dst
            .iter()
            .zip(&want)
            .filter(|(g, w)| g.to_bits() != w.to_bits())
            .count();
        if n_bad > 0 {
            let first = dst
                .iter()
                .zip(&want)
                .position(|(g, w)| g.to_bits() != w.to_bits())
                .unwrap();
            panic!(
                "{name}: {n_bad}/{} f32 bit mismatches; first at [{first}]: got {:?} ({:#010x}) want {:?} ({:#010x})",
                want.len(),
                dst[first],
                dst[first].to_bits(),
                want[first],
                want[first].to_bits()
            );
        }
    }
}

#[test]
fn multiband_end_to_end_bitexact() {
    let fx = load("multiband.json");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let num_bands = usize_at(case, "num_bands");
        let roi = case["dst_roi"].as_array().unwrap();
        let (rx, ry) = (
            roi[0].as_i64().unwrap() as i32,
            roi[1].as_i64().unwrap() as i32,
        );
        let (rw, rh) = (
            roi[2].as_u64().unwrap() as usize,
            roi[3].as_u64().unwrap() as usize,
        );

        let mut blender = MultiBandBlender::new(num_bands);
        blender.prepare(rx, ry, rw, rh);
        for feed in case["feeds"].as_array().unwrap() {
            let (w, h) = (usize_at(feed, "w"), usize_at(feed, "h"));
            let img_i16 = i16_vec(&feed["img"]);
            // The pipeline feeds CV_16S conversions of u8 images; the
            // fixtures store the CV_16S values (all within 0..=255).
            let img_u8: Vec<u8> = img_i16
                .iter()
                .map(|&v| u8::try_from(v).expect("fixture img out of u8 range"))
                .collect();
            let mask = GrayImage::new(w, h, u8_vec(&feed["mask"]));
            let corner = feed["corner"].as_array().unwrap();
            let tl = (
                corner[0].as_i64().unwrap() as i32,
                corner[1].as_i64().unwrap() as i32,
            );
            blender.feed(&img_u8, w, h, &mask, tl);
        }
        let (raw, cov) = blender.blend_i16();

        assert_i16_eq(name, &raw, &i16_vec(&case["result_i16"]));
        assert_eq!(
            cov.data,
            u8_vec(&case["result_mask"]),
            "{name}: coverage mask mismatch"
        );
        // And the u8 clamp used by the pipeline (np.clip / convertTo(CV_8U)).
        let clamped: Vec<u8> = raw.iter().map(|&v| v.clamp(0, 255) as u8).collect();
        assert_eq!(clamped, u8_vec(&case["result_u8"]), "{name}: u8 result");
    }
}

#[test]
fn num_bands_formula_matches_oracle() {
    let fx = load("num_bands.json");
    for case in fx["cases"].as_array().unwrap() {
        let (w, h) = (usize_at(case, "w"), usize_at(case, "h"));
        assert_eq!(
            num_bands_for(w, h),
            usize_at(case, "num_bands"),
            "num_bands_for({w}, {h})"
        );
    }
}
