//! BlocksGainCompensator parity vs the OpenCV oracle dumps
//! (tools/reference/dumps/*/gains, generated by tools/reference/oracle.py:
//! `cv2.detail_BlocksGainCompensator().feed(...)` + `getMatGains()` on the
//! seam-scale warped images).
//!
//! Skips silently when dumps are absent. Run with `-- --nocapture` for the
//! per-set diff metrics.

use std::path::{Path, PathBuf};

use panoloom_core::exposure::{BlocksGainCompensator, RgbImage};
use panoloom_core::imgproc::GrayImage;

fn dumps_dir(set: &str) -> Option<PathBuf> {
    let p =
        Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("../../tools/reference/dumps/{set}"));
    (p.join("gains").exists() && p.join("warped").exists()).then_some(p)
}

fn load_png_rgb(path: &Path) -> RgbImage {
    let decoder = png::Decoder::new(std::io::BufReader::new(std::fs::File::open(path).unwrap()));
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0; reader.output_buffer_size().unwrap()];
    let info = reader.next_frame(&mut buf).unwrap();
    buf.truncate(info.buffer_size());
    let (w, h) = (info.width as usize, info.height as usize);
    assert_eq!(
        info.color_type,
        png::ColorType::Rgb,
        "expected RGB png: {path:?}"
    );
    RgbImage::new(w, h, buf)
}

fn load_png_gray(path: &Path) -> GrayImage {
    let decoder = png::Decoder::new(std::io::BufReader::new(std::fs::File::open(path).unwrap()));
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0; reader.output_buffer_size().unwrap()];
    let info = reader.next_frame(&mut buf).unwrap();
    buf.truncate(info.buffer_size());
    assert_eq!(
        info.color_type,
        png::ColorType::Grayscale,
        "expected grayscale png: {path:?}"
    );
    GrayImage::new(info.width as usize, info.height as usize, buf)
}

/// Minimal .npy (v1.0) reader for 2-D little-endian f32 arrays.
fn load_npy_f32_2d(path: &Path) -> (usize, usize, Vec<f32>) {
    let raw = std::fs::read(path).unwrap();
    assert_eq!(&raw[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([raw[8], raw[9]]) as usize;
    let header = std::str::from_utf8(&raw[10..10 + header_len]).unwrap();
    assert!(header.contains("'<f4'"), "not f32: {header}");
    assert!(header.contains("'fortran_order': False"));
    let shape_str = header
        .split("'shape':")
        .nth(1)
        .unwrap()
        .split('(')
        .nth(1)
        .unwrap()
        .split(')')
        .next()
        .unwrap();
    let dims: Vec<usize> = shape_str
        .split(',')
        .filter_map(|s| s.trim().parse().ok())
        .collect();
    assert_eq!(dims.len(), 2, "shape: {shape_str}");
    let payload = &raw[10 + header_len..];
    assert_eq!(payload.len(), dims[0] * dims[1] * 4);
    let data = payload
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (dims[0], dims[1], data)
}

#[derive(serde::Deserialize)]
struct CornersJson {
    #[allow(dead_code)]
    scale: f64,
    corners: Vec<(i32, i32)>,
    sizes: Vec<(i32, i32)>,
}

fn run_set(set: &str) {
    let Some(dir) = dumps_dir(set) else {
        eprintln!("SKIP {set}: oracle dumps not present");
        return;
    };

    let meta: CornersJson =
        serde_json::from_str(&std::fs::read_to_string(dir.join("warped/corners.json")).unwrap())
            .unwrap();
    let n = meta.corners.len();

    let mut images = Vec::with_capacity(n);
    let mut masks = Vec::with_capacity(n);
    for i in 0..n {
        let img = load_png_rgb(&dir.join(format!("warped/img_{i:03}.png")));
        let mask = load_png_gray(&dir.join(format!("warped/mask_{i:03}.png")));
        assert_eq!(
            (img.width as i32, img.height as i32),
            meta.sizes[i],
            "{set} img {i} size mismatch vs corners.json"
        );
        images.push(img);
        masks.push(mask);
    }

    let comp = BlocksGainCompensator::feed(&meta.corners, &images, &masks);

    let mut max_abs = 0f64;
    let mut max_rel = 0f64;
    let mut exact = 0usize;
    let mut total = 0usize;
    for i in 0..n {
        let (rows, cols, oracle) = load_npy_f32_2d(&dir.join(format!("gains/gain_{i:03}.npy")));
        let gm = &comp.gain_maps()[i];
        assert_eq!(
            (gm.height, gm.width),
            (rows, cols),
            "{set} gain map {i} shape"
        );
        for (&ours, &theirs) in gm.data.iter().zip(&oracle) {
            let d = (ours as f64 - theirs as f64).abs();
            max_abs = max_abs.max(d);
            max_rel = max_rel.max(d / (theirs.abs() as f64).max(1e-12));
            exact += (ours == theirs) as usize;
            total += 1;
        }
    }

    println!(
        "{set}: {n} gain maps, {total} coeffs, bit-exact {exact}/{total}, \
         max abs diff {max_abs:.3e}, max rel diff {max_rel:.3e}"
    );
    assert!(
        max_abs < 1e-6,
        "{set}: gain map max abs diff {max_abs:.3e} (rel {max_rel:.3e}) exceeds 1e-6"
    );
}

#[test]
fn blocks_gain_maps_vs_oracle_ring() {
    run_set("ring_kloppenheim_06");
}

#[test]
fn blocks_gain_maps_vs_oracle_sphere() {
    run_set("sphere_kloppenheim_06");
}
