import { chromium } from "playwright";
import { readdirSync } from "node:fs";
import path from "node:path";
const dir = process.env.SET;
const files = readdirSync(dir).filter(f=>/\.(png|jpe?g)$/i.test(f) && f!=="preview.png").sort().map(f=>path.join(dir,f));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errs=[]; page.on("pageerror", e=>{errs.push(e.message); console.log("PAGEERROR:", e.message);});
await page.addInitScript(() => { delete window.showSaveFilePicker; });
await page.goto("http://localhost:4173", { waitUntil: "networkidle" });
await page.waitForSelector("text=engine ready", { timeout: 30000 });
await page.setInputFiles('input[type="file"]', files);
await page.waitForSelector(`text=${files.length} shots`, { timeout: 180000 });
await page.click("button.align-btn:not(.ghost)");
await page.waitForSelector(".viewer canvas", { timeout: 3000000 });
console.log("stitched:", (await page.locator(".bar-status").textContent()).trim());
const opts = await page.locator("select.export-size option").evaluateAll(e=>e.map(o=>({v:o.value,t:o.textContent})));
const ceil = opts.find(o=>/largest/i.test(o.t));
await page.selectOption("select.export-size", ceil.v);
console.log("exporting at", ceil.v, "px ...");
const t0 = Date.now();
const dl = page.waitForEvent("download", { timeout: 3000000 }).catch(()=>null);
await page.click('button:has-text("Export JPEG")');
const d = await dl;
console.log(`EXPORT: ${d ? await d.suggestedFilename() : "(timed out)"} in ${((Date.now()-t0)/60000).toFixed(1)} min`);
if (d) await d.saveAs("/tmp/pano137-full.jpg");
console.log("errors:", (await page.locator(".error").allTextContents()).filter(Boolean), errs.length?errs:"none");
await browser.close();
